### ISSUE TITLE
Max Range on Setup for Groups?

### ISSUE THREAD

**Issue by CloudeLecaw** [Ugleh/RedstoneProximitySensor#15]
Is it possible to add max_range: settings to the group settings?

```
limiter:
  player:
    amount: 40
    max_range: 15
    default: true
  admin:
    amount: -1
    max_range: 40
    default: op
```

Player with the default permision will only be able to set their max range of 15 while op and admins coulds set a max range of 40.
This would allow admins builders and OPs to set higher ranges that players in the massive useage cant use.
